/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemosRayTracingRouteImport } from './routes/demos/ray-tracing'
import { Route as DemosPeerMazeRouteImport } from './routes/demos/peer-maze'
import { Route as DemosHourglassRouteImport } from './routes/demos/hourglass'
import { Route as DemosFractalRouteImport } from './routes/demos/fractal'
import { Route as DemosCounterRouteImport } from './routes/demos/counter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosRayTracingRoute = DemosRayTracingRouteImport.update({
  id: '/demos/ray-tracing',
  path: '/demos/ray-tracing',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosPeerMazeRoute = DemosPeerMazeRouteImport.update({
  id: '/demos/peer-maze',
  path: '/demos/peer-maze',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosHourglassRoute = DemosHourglassRouteImport.update({
  id: '/demos/hourglass',
  path: '/demos/hourglass',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosFractalRoute = DemosFractalRouteImport.update({
  id: '/demos/fractal',
  path: '/demos/fractal',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosCounterRoute = DemosCounterRouteImport.update({
  id: '/demos/counter',
  path: '/demos/counter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demos/counter': typeof DemosCounterRoute
  '/demos/fractal': typeof DemosFractalRoute
  '/demos/hourglass': typeof DemosHourglassRoute
  '/demos/peer-maze': typeof DemosPeerMazeRoute
  '/demos/ray-tracing': typeof DemosRayTracingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demos/counter': typeof DemosCounterRoute
  '/demos/fractal': typeof DemosFractalRoute
  '/demos/hourglass': typeof DemosHourglassRoute
  '/demos/peer-maze': typeof DemosPeerMazeRoute
  '/demos/ray-tracing': typeof DemosRayTracingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demos/counter': typeof DemosCounterRoute
  '/demos/fractal': typeof DemosFractalRoute
  '/demos/hourglass': typeof DemosHourglassRoute
  '/demos/peer-maze': typeof DemosPeerMazeRoute
  '/demos/ray-tracing': typeof DemosRayTracingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demos/counter'
    | '/demos/fractal'
    | '/demos/hourglass'
    | '/demos/peer-maze'
    | '/demos/ray-tracing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demos/counter'
    | '/demos/fractal'
    | '/demos/hourglass'
    | '/demos/peer-maze'
    | '/demos/ray-tracing'
  id:
    | '__root__'
    | '/'
    | '/demos/counter'
    | '/demos/fractal'
    | '/demos/hourglass'
    | '/demos/peer-maze'
    | '/demos/ray-tracing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemosCounterRoute: typeof DemosCounterRoute
  DemosFractalRoute: typeof DemosFractalRoute
  DemosHourglassRoute: typeof DemosHourglassRoute
  DemosPeerMazeRoute: typeof DemosPeerMazeRoute
  DemosRayTracingRoute: typeof DemosRayTracingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/ray-tracing': {
      id: '/demos/ray-tracing'
      path: '/demos/ray-tracing'
      fullPath: '/demos/ray-tracing'
      preLoaderRoute: typeof DemosRayTracingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/peer-maze': {
      id: '/demos/peer-maze'
      path: '/demos/peer-maze'
      fullPath: '/demos/peer-maze'
      preLoaderRoute: typeof DemosPeerMazeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/hourglass': {
      id: '/demos/hourglass'
      path: '/demos/hourglass'
      fullPath: '/demos/hourglass'
      preLoaderRoute: typeof DemosHourglassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/fractal': {
      id: '/demos/fractal'
      path: '/demos/fractal'
      fullPath: '/demos/fractal'
      preLoaderRoute: typeof DemosFractalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/counter': {
      id: '/demos/counter'
      path: '/demos/counter'
      fullPath: '/demos/counter'
      preLoaderRoute: typeof DemosCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemosCounterRoute: DemosCounterRoute,
  DemosFractalRoute: DemosFractalRoute,
  DemosHourglassRoute: DemosHourglassRoute,
  DemosPeerMazeRoute: DemosPeerMazeRoute,
  DemosRayTracingRoute: DemosRayTracingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
